import { defineField, defineType } from 'sanity';

export const room = defineType({
  name: 'room',
  title: 'Rooms',
  type: 'document',
  fields: [
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name_en' } }),
    defineField({ name: 'name_en', title: 'Name (English)', type: 'string' }),
    defineField({ name: 'name_ka', title: 'Name (Georgian)', type: 'string' }),
    defineField({ name: 'name_ru', title: 'Name (Russian)', type: 'string' }),
    defineField({ name: 'name_tr', title: 'Name (Turkish)', type: 'string' }),
    defineField({ name: 'name_he', title: 'Name (Hebrew)', type: 'string' }),
    defineField({ name: 'name_ar', title: 'Name (Arabic)', type: 'string' }),
    defineField({ name: 'shortDescription_en', title: 'Short Description (English)', type: 'text' }),
    defineField({ name: 'shortDescription_ka', title: 'Short Description (Georgian)', type: 'text' }),
    defineField({ name: 'shortDescription_ru', title: 'Short Description (Russian)', type: 'text' }),
    defineField({ name: 'shortDescription_tr', title: 'Short Description (Turkish)', type: 'text' }),
    defineField({ name: 'shortDescription_he', title: 'Short Description (Hebrew)', type: 'text' }),
    defineField({ name: 'shortDescription_ar', title: 'Short Description (Arabic)', type: 'text' }),
    defineField({ name: 'fullDescription_en', title: 'Full Description (English)', type: 'text' }),
    defineField({ name: 'fullDescription_ka', title: 'Full Description (Georgian)', type: 'text' }),
    defineField({ name: 'fullDescription_ru', title: 'Full Description (Russian)', type: 'text' }),
    defineField({ name: 'fullDescription_tr', title: 'Full Description (Turkish)', type: 'text' }),
    defineField({ name: 'fullDescription_he', title: 'Full Description (Hebrew)', type: 'text' }),
    defineField({ name: 'fullDescription_ar', title: 'Full Description (Arabic)', type: 'text' }),
    defineField({ name: 'size', title: 'Size (sqm)', type: 'number' }),
    defineField({ name: 'maxGuests', title: 'Max Guests', type: 'number' }),
    defineField({ name: 'amenities', title: 'Amenities', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'images', title: 'Images', type: 'array', of: [{ type: 'image' }] }),
    defineField({ name: 'priceUsd', title: 'Price (USD)', type: 'number' }),
    defineField({ name: 'priceGel', title: 'Price (GEL)', type: 'number' }),
    defineField({ name: 'order', title: 'Order', type: 'number' }),
  ],
});
